version: "3.5"

services:
    api:
        build: ./api
        image: node:16.15.0
        working_dir: /api
        restart: always
        container_name: api
        links:
            - db:${MYSQL_HOST}
        depends_on:
            - db
        ports:
            - "${API_PORT}:${API_PORT}"
        volumes:
            - ./api:/api
        expose:
            - "${API_PORT}"
        command: "yarn run start:dev"
        env_file: .env

    db:
        image: mysql:5.7
        container_name: ${MYSQL_HOST}
        volumes:
            - ./database/data:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"
        environment:
            MYSQL_TCP_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    php-admin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db:${MYSQL_HOST}
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_HOST: ${MYSQL_HOST}
            PMA_PORT: ${MYSQL_PORT}
